// automatically generated by the FlatBuffers compiler, do not modify

package fbs

const (
	PacketNONE = 0
	PacketServer = 1
	PacketSpawn = 2
	PacketPerception = 3
	PacketControls = 4
)

var EnumNamesPacket = map[int]string{
	PacketNONE:"NONE",
	PacketServer:"Server",
	PacketSpawn:"Spawn",
	PacketPerception:"Perception",
	PacketControls:"Controls",
}

