// automatically generated by the FlatBuffers compiler, do not modify

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Server struct {
	_tab flatbuffers.Table
}

func GetRootAsServer(buf []byte, offset flatbuffers.UOffsetT) *Server {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Server{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Server) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Server) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Server) WorldRadius() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Server) MutateWorldRadius(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func ServerStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ServerAddWorldRadius(builder *flatbuffers.Builder, worldRadius float64) {
	builder.PrependFloat64Slot(0, worldRadius, 0.0)
}
func ServerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
