// automatically generated by the FlatBuffers compiler, do not modify

package fbs

const (
	SnapshotNONE = 0
	SnapshotShip = 1
	SnapshotBullet = 2
)

var EnumNamesSnapshot = map[int]string{
	SnapshotNONE:"NONE",
	SnapshotShip:"Ship",
	SnapshotBullet:"Bullet",
}

