// automatically generated by the FlatBuffers compiler, do not modify

package fbs

const (
	PacketNONE = 0
	PacketServer = 1
	PacketPlay = 2
	PacketSpawn = 3
	PacketPerception = 4
	PacketControls = 5
)

var EnumNamesPacket = map[int]string{
	PacketNONE:"NONE",
	PacketServer:"Server",
	PacketPlay:"Play",
	PacketSpawn:"Spawn",
	PacketPerception:"Perception",
	PacketControls:"Controls",
}

