// automatically generated by the FlatBuffers compiler, do not modify

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Play struct {
	_tab flatbuffers.Table
}

func GetRootAsPlay(buf []byte, offset flatbuffers.UOffsetT) *Play {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Play{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Play) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Play) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Play) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PlayStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PlayAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func PlayEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
