// automatically generated by the FlatBuffers compiler, do not modify

package fbs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Spawn struct {
	_tab flatbuffers.Table
}

func GetRootAsSpawn(buf []byte, offset flatbuffers.UOffsetT) *Spawn {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Spawn{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Spawn) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Spawn) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Spawn) Id() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Spawn) MutateId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func SpawnStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SpawnAddId(builder *flatbuffers.Builder, id uint64) {
	builder.PrependUint64Slot(0, id, 0)
}
func SpawnEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
