// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package downstream

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Bullet struct {
	_tab flatbuffers.Table
}

func GetRootAsBullet(buf []byte, offset flatbuffers.UOffsetT) *Bullet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Bullet{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Bullet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Bullet) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Bullet) Position(obj *Vector) *Vector {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Vector)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Bullet) Velocity(obj *Vector) *Vector {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Vector)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func BulletStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BulletAddPosition(builder *flatbuffers.Builder, position flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(position), 0)
}
func BulletAddVelocity(builder *flatbuffers.Builder, velocity flatbuffers.UOffsetT) {
	builder.PrependStructSlot(1, flatbuffers.UOffsetT(velocity), 0)
}
func BulletEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
