// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package downstream

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Death struct {
	_tab flatbuffers.Table
}

func GetRootAsDeath(buf []byte, offset flatbuffers.UOffsetT) *Death {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Death{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Death) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Death) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Death) Alive() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Death) MutateAlive(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func DeathStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DeathAddAlive(builder *flatbuffers.Builder, alive uint64) {
	builder.PrependUint64Slot(0, alive, 0)
}
func DeathEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
