// automatically generated by the FlatBuffers compiler, do not modify

package downstream

const (
	PacketNONE = 0
	PacketPong = 1
	PacketServerSettings = 2
	PacketSpawn = 3
	PacketPerception = 4
	PacketDeath = 5
)

var EnumNamesPacket = map[int]string{
	PacketNONE:"NONE",
	PacketPong:"Pong",
	PacketServerSettings:"ServerSettings",
	PacketSpawn:"Spawn",
	PacketPerception:"Perception",
	PacketDeath:"Death",
}

