// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package downstream

type Packet = byte
const (
	PacketNONE Packet = 0
	PacketServerSettings Packet = 1
	PacketSpawn Packet = 2
	PacketPerception Packet = 3
	PacketDeath Packet = 4
)

var EnumNamesPacket = map[Packet]string{
	PacketNONE:"NONE",
	PacketServerSettings:"ServerSettings",
	PacketSpawn:"Spawn",
	PacketPerception:"Perception",
	PacketDeath:"Death",
}

