// automatically generated by the FlatBuffers compiler, do not modify

package downstream

const (
	PacketNONE = 0
	PacketServerSettings = 1
	PacketSpawn = 2
	PacketPerception = 3
	PacketDeath = 4
)

var EnumNamesPacket = map[int]string{
	PacketNONE:"NONE",
	PacketServerSettings:"ServerSettings",
	PacketSpawn:"Spawn",
	PacketPerception:"Perception",
	PacketDeath:"Death",
}

