// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package downstream

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ServerSettings struct {
	_tab flatbuffers.Table
}

func GetRootAsServerSettings(buf []byte, offset flatbuffers.UOffsetT) *ServerSettings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ServerSettings{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ServerSettings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ServerSettings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ServerSettings) WorldRadius() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ServerSettings) MutateWorldRadius(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func ServerSettingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ServerSettingsAddWorldRadius(builder *flatbuffers.Builder, worldRadius float64) {
	builder.PrependFloat64Slot(0, worldRadius, 0.0)
}
func ServerSettingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
