// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package downstream

type Snapshot = byte
const (
	SnapshotNONE Snapshot = 0
	SnapshotShip Snapshot = 1
	SnapshotBullet Snapshot = 2
)

var EnumNamesSnapshot = map[Snapshot]string{
	SnapshotNONE:"NONE",
	SnapshotShip:"Ship",
	SnapshotBullet:"Bullet",
}

