// automatically generated by the FlatBuffers compiler, do not modify

package upstream

const (
	PacketNONE = 0
	PacketPing = 1
	PacketSpawn = 2
	PacketControls = 3
)

var EnumNamesPacket = map[int]string{
	PacketNONE:"NONE",
	PacketPing:"Ping",
	PacketSpawn:"Spawn",
	PacketControls:"Controls",
}

