// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package upstream

type Packet = byte
const (
	PacketNONE Packet = 0
	PacketSpawn Packet = 1
	PacketControls Packet = 2
)

var EnumNamesPacket = map[Packet]string{
	PacketNONE:"NONE",
	PacketSpawn:"Spawn",
	PacketControls:"Controls",
}

