// automatically generated by the FlatBuffers compiler, do not modify

package upstream

const (
	PacketNONE = 0
	PacketSpawn = 1
	PacketControls = 2
)

var EnumNamesPacket = map[int]string{
	PacketNONE:"NONE",
	PacketSpawn:"Spawn",
	PacketControls:"Controls",
}

