// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package upstream

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Spawn struct {
	_tab flatbuffers.Table
}

func GetRootAsSpawn(buf []byte, offset flatbuffers.UOffsetT) *Spawn {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Spawn{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Spawn) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Spawn) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Spawn) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SpawnStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SpawnAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func SpawnEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
